PowaNota/PowaNota/Models/Nota.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nota1.Models
{
    public class Nota
    {
        public int id;
        public Tipo tipo = new Tipo();
        public string titulo;
        public DateTime data = DateTime.Now.Date;
        public List<Texto> textos =  new  List<Texto>();
        public List<Topico> topicos= new  List<Topico>();

       


    }
}

PowaNota/PowaNota/Controllers/NotaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Nota1.Models;
using Nota1.Sessao;
using Newtonsoft.Json;
using System.Net;
using Nota1.DTO;
using Newtonsoft.Json.Linq;
using Nota1.Util;
using sessao = Nota1.Sessao.Session;

namespace Nota1.Controllers
{
    public class NotaController : Controller
    {
        static List<Nota> listaNota = new List<Nota>();
        static List<Topico> listaTopico = new List<Topico>();
        static List<Tipo> listaTipo = new List<Tipo>();


        // GET: Nota
        public ActionResult Index()
        {
            return View();
        }
        //Metodo de criar 

        public ActionResult Create()
        {
            //Recuperar Lista de Topicos
            //Recuperar Lista de Tipos

            try
            {
                #region WsTopicos

                String jsonRecebido = WebService.downloadJson("/AtributosNotas/recuperarTopico");

                GenericDTO dtoTopico = JsonConvert.DeserializeObject<GenericDTO>(jsonRecebido);
                dtoTopico.payload = ((JArray)dtoTopico.payload).ToObject<List<Topico>>();

                jsonRecebido = WebService.downloadJson("/AtributosNotas/recuperarTipo");
                GenericDTO dtoTipo = JsonConvert.DeserializeObject<GenericDTO>(jsonRecebido);
                dtoTipo.payload = ((JArray)dtoTipo.payload).ToObject<List<Tipo>>();

                if (dtoTopico.operacaoSucedida && dtoTipo.operacaoSucedida)
                {
                    listaTopico = (List<Topico>)dtoTopico.payload;
                    listaTipo = (List<Tipo>)dtoTipo.payload;
                }
                else
                {
                    Response.Write(dtoTopico.mensagemErro);
                    return new EmptyResult();
                }
                #endregion

              
            }
            catch (Exception e)
            {
                Response.Write("Erro!:" + e.Message);
                return View();
            }
         
            ViewBag.ListaTipo = listaTipo;
            ViewBag.ListaTopico = listaTopico;

            ViewBag.tela = 1;

            return View();
        }

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            ViewBag.ListaTipo = listaTipo;
            ViewBag.ListaTopico = listaTopico;
            try
            {
                Nota nota = new Nota()
                {
                    titulo = collection["Titulo"],
                };

                foreach (Tipo t in listaTipo)
                {
                    if (t.id == int.Parse(collection["tipos"]))
                    {
                        nota.tipo = t;
                    }
                }
                nota.textos = new List<Texto>();
                nota.textos.Add(new Texto
                {
                    conteudo = collection["Textos"]
                });

                string topicosStr = collection["topicos"];
                string[] listTopicoStr = topicosStr.Split(',');
                nota.topicos = new List<Topico>();

                foreach (Topico t in listaTopico)
                {
                    foreach (string topico in listTopicoStr)
                    {
                        if (t.id.Equals(int.Parse(topico)))
                            nota.topicos.Add(t);
                    }
                };

                string jsonEnvio = JsonConvert.SerializeObject(nota);

                WebService.uploadJson("/Nota/criar", jsonEnvio);

            }

            catch (Exception e)
            {
                Response.Write(e.Message);
                return View();
            }

            ViewBag.jsMosalSucesso = "1";
            ViewBag.tela = 1;
            return View();
        }
    }
}

PowaNota/PowaNota/Views/Nota/Create.cshtml
@{
    ViewBag.Title = "Crie sua Anotação";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using Nota1.Models
@model Nota

<h2>Create</h2>
@using (Html.BeginForm("Create","Nota",FormMethod.Post,new {id = "criarNota"}))

{
    @Html.AntiForgeryToken()
    <div class="form-horizontal ">
        <h4>Nota</h4>
        <hr/>
        @Html.ValidationSummary(true, "Erro:", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.titulo,"Titulo",  new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control" ,id = "titulo"}})
                    @Html.ValidationMessageFor(model => model.titulo, "", new { @class = "text-danger" })
                </div>
            </div>

        <div class="form-group">
            @Html.Label("Tipo de Nota", new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @foreach (var listaTipo in (List<Tipo>)ViewBag.ListaTipo)
                {
                    <input type="radio" name="tipos" id="radio-choice-v-2a" value="@listaTipo.id" checked="true">
                    <label for="radio-choice-v-2a">@listaTipo.nome</label>
                }
                @Html.ValidationMessageFor(model => model.tipo, "", new { @class = "text-danger" })
                <br/>
                @Html.TextArea("Textos", "", new { @class = "form-control col-md-3 required", placeholder = "Texto(1000 caracteres no max.)", maxlength = "1000" })
                </div>
        </div>
        <div class="form-group">
            @Html.Label("Selecione os topicos", new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                <select id="multiselectTopico" name="topicos" multiple="multiple" required="true">
                @foreach (var listaTopico in (List<Topico>)ViewBag.ListaTopico)
                {
                    <option  value="@listaTopico.id">@listaTopico.nome</option>
                }
                </select>

            </div>
        </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Criar" class="btn btn-default" onsubmit="mostrarModalCriarNota()"/>
                </div>
            </div>
        </div>


        

    
}

PowaNota/PowaNota/Views/Nota/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}