PowaNota/PowaNota/Controllers/NotaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Nota1.Models;
using Nota1.Sessao;
using Newtonsoft.Json;
using System.Net;
using Nota1.DTO;
using Newtonsoft.Json.Linq;
using Nota1.Util;
using sessao = Nota1.Sessao.Session;

namespace Nota1.Controllers
{
    public class NotaController : Controller
    {
        static List<Nota> listaNota = new List<Nota>();
        static List<Topico> listaTopico = new List<Topico>();
        static List<Tipo> listaTipo = new List<Tipo>();


        // GET: Nota
        public ActionResult Index()
        {
            return View();
        }
        //Metodo de criar 

        public ActionResult Create()
        {
            //Recuperar Lista de Topicos
            //Recuperar Lista de Tipos

            try
            {
                #region WsTopicos

                String jsonRecebido = WebService.downloadJson("/AtributosNotas/recuperarTopico");

                GenericDTO dtoTopico = JsonConvert.DeserializeObject<GenericDTO>(jsonRecebido);
                dtoTopico.payload = ((JArray)dtoTopico.payload).ToObject<List<Topico>>();

                jsonRecebido = WebService.downloadJson("/AtributosNotas/recuperarTipo");
                GenericDTO dtoTipo = JsonConvert.DeserializeObject<GenericDTO>(jsonRecebido);
                dtoTipo.payload = ((JArray)dtoTipo.payload).ToObject<List<Tipo>>();

                if (dtoTopico.operacaoSucedida && dtoTipo.operacaoSucedida)
                {
                    listaTopico = (List<Topico>)dtoTopico.payload;
                    listaTipo = (List<Tipo>)dtoTipo.payload;
                }
                else
                {
                    Response.Write(dtoTopico.mensagemErro);
                    return new EmptyResult();
                }
                #endregion

              
            }
            catch (Exception e)
            {
                Response.Write("Erro!:" + e.Message);
                return View();
            }
         
            ViewBag.ListaTipo = listaTipo;
            ViewBag.ListaTopico = listaTopico;

            ViewBag.tela = 1;

            return View();
        }

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            ViewBag.ListaTipo = listaTipo;
            ViewBag.ListaTopico = listaTopico;
            try
            {
                Nota nota = new Nota()
                {
                    titulo = collection["Titulo"],
                };

                foreach (Tipo t in listaTipo)
                {
                    if (t.id == int.Parse(collection["tipos"]))
                    {
                        nota.tipo = t;
                    }
                }
                nota.textos = new List<Texto>();
                nota.textos.Add(new Texto
                {
                    conteudo = collection["Textos"]
                });

                string topicosStr = collection["topicos"];
                string[] listTopicoStr = topicosStr.Split(',');
                nota.topicos = new List<Topico>();

                foreach (Topico t in listaTopico)
                {
                    foreach (string topico in listTopicoStr)
                    {
                        if (t.id.Equals(int.Parse(topico)))
                            nota.topicos.Add(t);
                    }
                };

                string jsonEnvio = JsonConvert.SerializeObject(nota);

                WebService.uploadJson("/Nota/criar", jsonEnvio);

            }

            catch (Exception e)
            {
                Response.Write(e.Message);
                return View();
            }

            ViewBag.jsMosalSucesso = "1";
            ViewBag.tela = 1;
            return View();
        }
    }
}

PowaNota/PowaNota/Controllers/PastaController.cs
using Newtonsoft.Json;
using Nota1.DTO;
using Nota1.Util;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using Newtonsoft.Json.Linq;
using sessao = Nota1.Sessao.Session;
using Nota1.Models;
using System.Text.RegularExpressions;
using PowaNota.Util;

namespace PowaNota.Controllers
{
    public class PastaController : Controller
    {

        public ActionResult List()
        {
            if (sessao.usuarioLogado != null)
            {
                var jsonPastas = WebService.downloadJson("/Pasta/recuperarPorIdUsuario/" + sessao.usuarioLogado.id.ToString());
                GenericDTO dto = JsonConvert.DeserializeObject<GenericDTO>(jsonPastas);
                dto.payload = ((JArray)dto.payload).ToObject<List<Pasta>>();
                ViewBag.json_pastas = PastaJsonConverter.pastaConverter(((List<Pasta>)dto.payload));
            }

            ViewBag.tela = 0;
            return View();
        }
    }
}

PowaNota/PowaNota/Controllers/TopicoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Nota1.Models;
using Newtonsoft.Json;
using System.Net;
using Nota1.Util;

namespace Nota1.Controllers
{
    public class TopicoController : Controller
    {
        public ActionResult Create()
        {
            ViewBag.tela = 2;
            return View();
        }

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                Topico topico = new Topico
                {
                    nome = collection["Nome"]
                };

                string jsonEnvio = JsonConvert.SerializeObject(topico);

                WebService.uploadJson("/AtributosNotas/criarTopico", jsonEnvio);
            }

            catch (Exception e)
            {
                Response.Write(e.Message);
            }
            ViewBag.tela = 2;
            return View();

        }
    }
}

PowaNota/PowaNota/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Nota1.Models;
using Nota1.Sessao;
using sessao = Nota1.Sessao.Session;
using Newtonsoft.Json;
using Nota1.Util;

namespace Nota1.Controllers
{
    public class UsuarioController : Controller
    {

        static List<Usuario> listaUsuarios = new List<Usuario>();
        // GET: Usuario
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Create()
        {
            return View();
        }
        //Metodo de criar 
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                Usuario usuario = new Usuario()
                {
                    email = collection["email"],
                    login = collection ["login"],
                    senha = collection["senha"]
                };

                string jsonEnvio = JsonConvert.SerializeObject(usuario);

                WebService.uploadJson("/Usuario/criar", jsonEnvio);

            }

            catch (Exception e)
            {
                Response.Write(e.Message);
                return View();
            }

            ViewBag.login = collection["login"];

            return View();
        }
         
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(FormCollection fc)
        {
            string erro;
            if (sessao.logar(fc["login"],fc["senha"],out erro))
            {
                return RedirectToAction("Index","Nota");
            }

            ViewBag.erro = erro;

            return Login();
        }
    }
}

PowaNota/PowaNota/Views/Shared/Inicial.cshtml
@{
    ViewBag.Title = "PowerNota";
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="icon" href="@Url.Content("~/Content/imgs/favicon.ico")" />
</head>
<body id="page-top" class="index">
    <!-- Navigation -->
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                @Html.ActionLink("PowerNota", "Index", "Home", new object { },new { @class = "navbar-brand"})
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll">
                        @Html.ActionLink("Sobre", "Index", "Home")">
                    </li>
                    <li class="page-scroll">
                        @Html.ActionLink("Logar","Login","Usuario")">
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    <header>
        <section class="success" id="sobre">
            @RenderBody()
        </section>
    </header>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PowaNota/PowaNota/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using user = Nota1.Sessao.Session;
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="icon" href="@Url.Content("~/Content/imgs/favicon.ico")" />
</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header logo">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               @Html.ActionLink("PowerNota","Index","Nota", new { @class= "navbar-brand powanota" } )
               <p class="navbar-brand beta">beta</p>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-user"></i>@(user.usuarioLogado != null ? user.usuarioLogado.login : "Não Logado")<b class="caret"></b></a>
                    <ul class="dropdown-menu" style="min-width:150px">
                        <li>
                            <a href="#" data-toggle="modal" data-target="#implementar"><i class="glyphicon glyphicon-list-alt"></i> Perfil</a>
                        </li>
                        <li>
                            <a href="#" data-toggle="modal" data-target="#implementar"><i class="glyphicon glyphicon-envelope"></i> Inbox</a>
                        </li>
                        <li>
                            <a href="#" data-toggle="modal" data-target="#implementar"><i class="glyphicon glyphicon-cog"></i> Configuração</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                           @Html.ActionLink("Sair","logout","Home",new object { }, new { @class = "glyphicon glyphicon-off" })
                            @{
                                Session.Abandon();
                            }
                        </li>
                    </ul>
                </li>
            </ul> 
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li class="@(ViewBag.tela == 0 ? "active" : "")">
                        @Html.ActionLink("Notas", "List", "Pasta")
                    </li>
                    <li class="@(ViewBag.tela == 1 ? "active" : "")">
                        @Html.ActionLink("Criar Nota", "Create", "Nota")
                    </li>
                    <li class="@(ViewBag.tela == 2 ? "active" : "")">
                        @Html.ActionLink("Criar Tópicos", "Create", "Topico")
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>
        <div id="page-wrapper">
            <div class="container-fluid">
                @RenderBody()

                @Scripts.Render("~/bundles/jquery")
                @Scripts.Render("~/bundles/bootstrap")
                @Scripts.Render("~/bundles/jqueryval")
                @RenderSection("scripts", required: false)
            </div>
        </div>
        </div>

        <div id="modal" class="modal fade">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title text-danger" id="gridSystemModalLabel">Acesso Negado</h4>
                    </div>
                    <div class="modal-body">
                        <div class="text-danger">Logue antes de continuar</div>
                    </div>
                    <div class="modal-footer">
                         @Html.ActionLink("Login", "Login", "Usuario")
                    </div>
                </div>
            </div>
        </div>
        
        <div id="modalSuccess" class="modal fade">
            <div class="modal-dialog" role="document">
                <button type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title text-success" id="gridSystemModalLabel">Nota Criada!</h4>
                    </div>
                </div>
            </div>
        </div>
</body>


<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" id="implementar">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                
            </div>
            <div class="modal-body" >
                <h3 class="text-center text-warning glyphicon-font" > A ser implementado!</h3>
            </div>
        </div>
    </div>
</div>

</html>

<script>
    if(@ViewBag.IsLogado == "1"){
        mostrarModal()
    };
</script>

@if (ViewBag.jsMosalSucesso == "1")
{
<script>
            mostrarModalCriarNota();
</script>
}